# require_relative the required gems/libraries.
require 'active_record'
require 'logger'

# require_relative all of our ActiveRecord::Base objects.
require_relative 'app/models/customer.rb'
require_relative 'app/models/line_item.rb'
require_relative 'app/models/order.rb'
require_relative 'app/models/product.rb'
require_relative 'app/models/province.rb'

# Establish our connection to our serverless sqlite3 database.
ActiveRecord::Base.establish_connection :adapter => 'sqlite3', :database => 'db/development.sqlite3'

# For debugging purposes, uncomment this line to see the SQL generated by ActiveRecord:
# ActiveRecord::Base.logger = Logger.new(STDOUT)

# Uncomment this line to make the logger output look nicer in Windows.
# ActiveSupport::LogSubscriber.colorize_logging = false